# Generated by Django 6.1 on 2026-09-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
