# Generated by Django 6.1 on 2026-09-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_experience_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
