# Generated by Django 5.2.17 on 2026-09-21 05:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_education_thumbnail_alter_experience_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('email', 'Email'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('whatsapp', 'Whatsapp'), ('line', 'Line'), ('github', 'Github'), ('others', 'Lainnya')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
