# Generated by Django 5.2.17 on 2026-09-22 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('to', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
