# Generated by Django 5.2.17 on 2026-09-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_experience_starred_by_message_starred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
