# Generated by Django 5.2.17 on 2026-09-26 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_education_thumbnail_url_experience_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PM', 'Product Manager'), ('PM', 'Project Manager'), ('PS', 'Project Support'), ('Dev', 'Web Developer'), ('Des', 'Designer')], max_length=20)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('project_url', models.URLField(blank=True)),
                ('project_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
