# Generated by Django 5.2.17 on 2026-09-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='role',
        ),
    ]
