# Generated by Django 5.2.17 on 2026-09-26 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_category_project_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('tools', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Personal', 'Personal Project'), ('Group', 'Group Project')], max_length=20)),
                ('project_url', models.URLField(blank=True)),
                ('project_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
