# Generated by Django 5.2.17 on 2026-09-27 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_design'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_design', to=settings.AUTH_USER_MODEL),
        ),
    ]
